#!/bin/sh

SRCDIR=/workspaces/Smallwebserver/yaws-yaws-2.3.1
BUILDDIR=/workspaces/Smallwebserver/yaws-yaws-2.3.1
YAWS_VSN=2.3.1
INSTALL_BUILDER=${INSTALL_BUILDER:-/home/codespace/installbuilder-5.4.14}


echo packing release ${YAWS_VSN}

TAG="yaws-${YAWS_VSN}"
NAME_VERSION="yaws-${YAWS_VSN}"

# Add/update release tag
(cd ${SRCDIR} && git tag -f -a -m "version ${YAWS_VSN}" "$TAG")

# Create windows installer
#(cd ${BUILDDIR} && make mkinstaller INSTALL_BUILDER=${INSTALL_BUILDER} >/dev/null)

# Create distribution tarball
(cd ${BUILDDIR} && make dist > /dev/null)

echo release resides in ${BUILDDIR}/$NAME_VERSION.tar.gz
#echo release resides in ${BUILDDIR}/Yaws-${YAWS_VSN}-windows-installer.exe

echo "To push this do:"
#echo "git push origin revs/tags/yaws-${version}:revs/tags/yaws-${version}"
echo "git push --tags"

exit 0
