#!/bin/bash --

progname=`basename $0`
localstatedir=${prefix}/var

function usage () {
    cat <<EOF
usage: $progname <wob file>
EOF
    exit 1
}


if test $# -ne 2 ; then
	usage
fi

erl -noinput -pa $(localstatedir)/yaws/wiki/ebin -s wiki addFile $1 $2
